First Example for two independent variables

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

N = 50
x1 = np.random.randn(N)
x2 = np.random.randn(N)

y = 3 * x1 + 0.5 * x2

w1 = np.sum(y * x1) / np.sum(x1 * x1)
w2 = np.sum(y * x2) / np.sum(x2 * x2)

print(w1, w2)
pred = w1 * x1 + w2 * x2
plt.plot(y)
plt.plot(pred)
plt.legend(['y', 'pred'])
plt.show()




Example with two correlated variables

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

N = 50
x1 = np.random.randn(N)
x2 = x1 + np.random.randn(N)

y = 3 * x1 + 0.5 * x2

w1 = np.sum(y * x1) / np.sum(x1 * x1)
w2 = np.sum(y * x2) / np.sum(x2 * x2)

print(w1, w2)
pred = w1 * x1 + w2 * x2
plt.plot(y)
plt.plot(pred)
plt.legend(['y', 'pred'])
plt.show()

Solution for Correlated variables

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

N = 50
x1 = np.random.randn(N)
x2 = x1 + np.random.randn(N)

y = 3 * x1 + 0.5 * x2

# wx = x2 effect on x1
wx = np.sum(x1 * x2) / np.sum(x2 * x2)
#ex1 = x1 without x2 effect
ex1 = x1 - wx * x2
w1 = np.sum(y * ex1) / np.sum(ex1 * ex1)

wx = np.sum(x2 * x1) / np.sum(x1 * x1)
ex2 = x2 - wx * x1
w2 = np.sum(y * ex2) / np.sum(ex2 * ex2)

print(w1, w2)
pred = w1 * x1 + w2 * x2
plt.plot(y)
plt.plot(pred)
plt.legend(['y', 'pred'])
plt.show()

study on solution

In [87]:
import numpy as np
import matplotlib.pyplot as plt

N = 50

x1 = np.random.randn(N)
# create x2 independent or correlated from x1 
x2 = np.random.randn(N)

y = 3 * x1 + 0.5 * x2

# wx = x2 effect on x1
wx = np.sum(x1 * x2) / np.sum(x2 * x2)
print(f"Effect of x2 on x1 = {wx}")
#ex1 = x1 without x2 effect
ex1 = x1 - wx * x2
w1 = np.sum(y * ex1) / np.sum(ex1 * ex1)

wx = np.sum(x2 * x1) / np.sum(x1 * x1)
print(f"Effect of x1 on x2 = {wx}")
ex2 = x2 - wx * x1
w2 = np.sum(y * ex2) / np.sum(ex2 * ex2)
print(f"solution: w1 = {w1}, w2 = {w2}")

Effect of x2 on x1 = 0.16292514512746
Effect of x1 on x2 = 0.1028177401505337
solution: w1 = 2.9999999999999996, w2 = 0.4999999999999999


Bigger Example

In [13]:
import numpy as np
import matplotlib.pyplot as plt

N = 5
M = 2
xs = np.random.randn(M, N)
print(xs)
ws = np.random.randn(M)
print(ws)
ys = np.dot(ws, xs)
print(ys)



[[-0.59398141  0.50137293  0.61210177 -0.12765077  1.08017439]
 [ 2.67033214 -1.0862383  -0.51307329  0.4348522   1.98618431]]
[0.68815595 0.18133804]
[ 0.07548096  0.14804644  0.32818177 -0.00898839  1.10349921]
